export { getPaginateProductsWithImages} from './products/product-pagination'
export {getProductBySlug} from './products/get-product-by-slug'
export {getStockBySlug} from './products/get-stock-by-slug'
export  {authenticate, login} from './auth/login'
export  {logout} from './auth/logOut'
export {registerUser} from './auth/register'
export {getCountries} from './country/get-country'
export { setUserAddress } from './address/set-user-address'
export { deleteUserAddress } from './address/delete-user-address'
export { getUserAddress } from './address/get-user-address'
export { placeOrder } from './order/place-order'
export { getOrderById } from './order/get-order-by-id'
export { getOrdersByUser } from './order/get-orders-by-user'
export { setTransactionId } from './payments/set-transaction-id'
export { paypalCheckPayment } from './payments/paypal-check-payment'
export { getPaginatedOrders } from './order/get-paginated-orders'
export {getAllUsers} from './user/getAllUsers'
export {changeRoleUser} from './user/change-role-user'
export { getCategories } from './categories/get-categories'
export { createUpdateProduct } from './products/create-update-product'