export { getPaginateProductsWithImages} from './products/product-pagination'
export {getProductBySlug} from './products/get-product-by-slug'
export {getStockBySlug} from './products/get-stock-by-slug'
export  {authenticate, login} from './auth/login'
export  {logout} from './auth/logOut'
export {registerUser} from './auth/register'
export {getCountries} from './country/get-country'
export { setUserAddress } from './address/set-user-address'
export { deleteUserAddress } from './address/delete-user-address'